apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-aks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-aks-app
  template:
    metadata:
      labels:
        app: flask-aks-app
    spec:
      containers:
        - name: flask-aks-app
          image: chetdoc16/flask-aks-app:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          
